### ISSUE TITLE
Rebut wählt falsche Argumente aus

### ISSUE THREAD

**Issue by Tarmean** [hhucn/dbas#6]
https://github.com/hhucn/dbas/blob/a4d687edd7811b041d954ce4ce563ffa1f4ebad3/dbas/helper/dictionary/items.py#L380

Diese Zeile sollte den Support fall umkehren, also

    Argument.is_supportive == !db_argument.is_supportive,

**Comment by n2o** [comment]
Jep, könnte stimmen. Wir arbeiten dran, dankeschön!

**Comment by MrEbbinghaus** [comment]
Will be fixed in: 51cb728a4207e1fec2c060b7e3fa53db83f2d857

**Comment by MrEbbinghaus** [comment]
Resolved by: 51cb728a4207e1fec2c060b7e3fa53db83f2d857
