### ISSUE TITLE
Meet with Canonical Debate

### ISSUE THREAD

**Issue by Whathecode** [hhucn/dbas#7]
I recently ran into this project, and it seems like it might be worthwhile for the people maintaining it to get in touch with what is as far as I know the biggest group of people sharing ideas and discussing systems similar to D-BAS.

The Canonical Debate Lab: https://canonicaldebatelab.com/

We are a bunch of people from both academic and hobby backgrounds working on similar technologies and sharing ideas, trying to work towards a common shared architecture. The Slack group is the most active on this topic that I am aware of, and every now and then we have virtual meetings.

Slack: https://join.slack.com/t/canonicaldebatelab/shared_invite/enQtMzEzOTU3NzYyMDY3LTI4YzUxM2I0MjFjZDNlMzQxZDM4YTgwNDNlMTY3YWQwNjJhYjk0ODE1MGU5NzQ2MTAyNTFhZWRhMGNjMjAxNmE

It would be great to meet someone on this project and give a more detailed presentation on what it is all about and where you want to be headed. :)

**Comment by n2o** [comment]
Hi, nice to hear from you, do you have a new slack invitation link for us please?

**Comment by n2o** [comment]
You can send a mail to meter@hhu.de if you like

**Comment by bigokro** [comment]
Here it is: https://join.slack.com/t/canonicaldebatelab/shared_invite/zt-408acfmb-qhowbidwY0aKaET7wP_IEQ

I'll send you the link via email as well.
